$(document).ready(function() {
  $('.returnpics').hide();
  $('.returnchecks').hide();
  $('img').click(function(){
  	$(this).fadeOut('slow');
  });
   $('img').click(function(){
  	$('.returnpics').show('slow');
  });
  $('.returnpics').click(function(){
  	$('img').slideDown('slow');
  	 $('.returnpics').hide();
  });
  $('.box').click(function(){
  	$(this).fadeTo('slow',0);
  	$('.returnchecks').show('slow');
  });
  $('.returnchecks').click(function(){
  	$('.box').fadeTo('slow',1);
    $('.returnchecks').hide();
  });
});